fix: lifecycle link
yobta/stores pull request #47
Opened 2023-01-13 11:26 UTC by plusbpm

https://app.shortcut.com/sdlk/story/2355/lifecycle

2023-01-13 14:18 UTC, droganov requested changes
let's link it to: https://github.com/yobta/stores/blob/master/src/plugins/index.md#store-events
please

also on that page please remove the 2 lines for next, since it's no longer supported

2023-01-18 13:08 UTC, droganov approved these changes

2023-01-18 13:48 UTC, plusbpm commented
Rebased

2023-02-02 10:48 UTC, droganov approved these changes

2023-02-02 10:48 UTC, merged